/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Vercel Serverless Function — catch-all handler for all /api/* routes.
 * Imports the pre-bundled Express app from ./_app.cjs (built by esbuild
 * during vercel build) and delegates to it.
 *
 * Environment variables required (server-side only, NEVER exposed to browser):
 *   SUPABASE_URL             — Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY — Supabase service_role key (bypasses RLS)
 *
 * Routing: vercel.json rewrites ALL /api/* to this file.
 * The x-matched-path header (set by Vercel rewrites) carries the original
 * request path so Express can route correctly.
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';

let app: any;
let initLog: string[] = [];
let initDone = false;

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Handle CORS preflight — no imports needed
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,PATCH,OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type,x-operator-name,x-operator-role,x-operator-username,x-employee-id,x-security-pin');
    res.setHeader('Access-Control-Max-Age', '86400');
    return res.status(204).end();
  }

  // Restore original request path from Vercel rewrite.
  const matchedPath = req.headers['x-matched-path'] as string | undefined;
  if (matchedPath && matchedPath !== req.url) {
    req.url = matchedPath;
  }

  // Diagnostic endpoint — check env var availability without exposing values
  const reqPath = (req.url || '').split('?')[0];
  if (reqPath === '/api/__debug/env') {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    return res.status(200).json({
      supabaseUrlPresent: !!supabaseUrl,
      supabaseUrlLength: supabaseUrl ? supabaseUrl.length : 0,
      supabaseUrlStartsWith: supabaseUrl ? supabaseUrl.substring(0, 12) + '...' : 'MISSING',
      serviceKeyPresent: !!supabaseKey,
      serviceKeyLength: supabaseKey ? supabaseKey.length : 0,
      initDone,
      initLog,
    });
  }

  // Initialize Express app once (cold start), reuse across warm invocations
  if (!app) {
    try {
      // Import from pre-bundled file (built by esbuild in buildCommand)
      // @ts-expect-error — _app.cjs is generated by esbuild at build time
      const { createApp } = await import('./_app.cjs');
      const msg1 = '[Vercel] Loaded bundled Express app module.';
      console.log(msg1);
      initLog.push(msg1);

      const supabaseUrl = process.env.SUPABASE_URL;
      const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

      const envMsg = `[Vercel] SUPABASE_URL: ${supabaseUrl ? 'SET (' + supabaseUrl.length + ' chars)' : 'MISSING'}`;
      console.log(envMsg);
      initLog.push(envMsg);

      const keyMsg = `[Vercel] SUPABASE_SERVICE_ROLE_KEY: ${supabaseKey ? 'SET (' + supabaseKey.length + ' chars)' : 'MISSING'}`;
      console.log(keyMsg);
      initLog.push(keyMsg);

      let supabaseAdmin: any = null;
      if (supabaseUrl && supabaseKey) {
        const { createClient } = await import('@supabase/supabase-js');
        supabaseAdmin = createClient(supabaseUrl, supabaseKey);
        const msg2 = '[Vercel] Supabase service_role client initialized.';
        console.log(msg2);
        initLog.push(msg2);
      } else {
        const msg3 = '[Vercel] WARNING: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing — running without cloud persistence.';
        console.warn(msg3);
        initLog.push(msg3);
      }

      app = await createApp(supabaseAdmin);
      initDone = true;
      const msg4 = '[Vercel] Express app initialized with all ERP routes.';
      console.log(msg4);
      initLog.push(msg4);
    } catch (err: any) {
      const errMsg = `[Vercel] FATAL: Failed to initialize Express app: ${err?.message || String(err)}`;
      console.error(errMsg);
      initLog.push(errMsg);
      return res.status(500).json({
        error: 'Server initialization failed',
        message: err?.message || String(err),
        initLog,
      });
    }
  }

  // Set CORS response headers
  res.setHeader('Access-Control-Allow-Origin', '*');

  // Delegate to Express
  return app(req, res);
}

export const config = {
  api: {
    bodyParser: false,
  },
};
